### ISSUE TITLE
TypeScript Type/Interface

### ISSUE THREAD

**Issue by ricayanzon** [uhasker/getting-things-done-in-next-js#113]
A deep dive into TypeScript is obviously out of the scope of this book. Still, I think it might be better to use `interface` instead of `type` throughout the book, since you should always prefer interface to type:
- https://stackoverflow.com/a/65948871/25729744
- https://github.com/microsoft/TypeScript/wiki/Performance#preferring-interfaces-over-intersections

This way, the reader already gets used to use `interface` instead of `type`.

**Comment by uhasker** [comment]
This issue is much more complicated than the two links above suggest, see e.g. https://www.youtube.com/watch?v=zM9UPcIyyhQ for a good discussion (the takeaway is that you should use `type`s unless you need an `interface` feature because `interface` has some weird behavior on the margins).

Fundamentally, it's a bikeshedding decision for 99% of for what you realistically encounter in the real world and not really something that's important for this book.
